---
class: 4
flags: 0x0000
unid: OFF23461967B650016-ON003579E5802577C8
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: WEB-INF/extlib-namespace.xsp-config
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $FlagsExt
    type: text
    data: w
    signed: true
  - name: $Revisions
    type: time
    data:
      - data: "2010-10-26T10:44:06.43+01:00"
        dst: true
      - data: "2011-08-30T20:50:49.35-04:00"
        dst: true
      - data: "2011-10-06T16:05:42.37+01:00"
        dst: true
      - data: "2011-10-14T08:39:57.61+01:00"
        dst: true
  - name: $TITLE
    type: text
    data: WEB-INF/extlib-namespace.xsp-config
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []