---
class: 4
flags: 0x0000
unid: OFAE4E4BA69AC230C6-ON00527B1085257594
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: WEB-INF/faces-config.xml
    signed: true
  - name: $Flags
    type: text
    data: ~Cg4
  - name: $FlagsExt
    type: text
    data: w
    signed: true
  - name: $LANGUAGE
    type: text
    data: en
    signed: true
  - name: $Revisions
    type: time
    data:
      - data: "2009-04-10T11:00:54.71-04:00"
        dst: true
      - data: "2010-12-15T14:47:19.52-00:00"
      - data: "2011-08-30T20:50:44.25-04:00"
        dst: true
      - data: "2011-10-06T16:05:42.39+01:00"
        dst: true
      - data: "2011-10-14T08:39:57.63+01:00"
        dst: true
      - data: "2011-10-26T12:23:01.68+01:00"
        dst: true
  - name: $TITLE
    type: text
    data: WEB-INF/faces-config.xml
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []