---
class: 8
flags: 0x0000
unid: OF1A2A2633DCB1FA49-ON0039F074802577C2
items:
  - name: $Collation
    type_num: 2
    type: opaque
    opaque: BgAAAABE
  - name: $Comment
    type: text
    data: ""
    signed: true
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $Flags
    type: text
    data: Y
  - name: $Formula
    type: formula
    data: " @All"
    opaque: MgAFABoAFQACAAkABAAkQ29uZmxpY3QkUkVGAAQABAAAAAgAZgADAAcACgAEAAlMMVM=
    signed: true
  - name: $FormulaClass
    type: text
    data: "1"
    signed: true
  - name: $Index
    type: text
    data: ""
    signed: true
  - name: $TITLE
    type: text
    data: default|default
    signed: true
  - name: $VIEWFORMAT
    type_num: 5
    type: opaque
    opaque: |
      AQABAAEACAAAAFZDAAACAAEACgAKAFAAAQAACgAAAAAAAAAAAAICAAAAJDAjCgAAAAgAkgADAAEFAQAE
      AH9BMP8mAAEAAAABAQAJAQAACgEBDgoAAAEArSsBAAEAAQAAAAAAAAAAAFdDAQEACQAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAABCAAAAAAABAP///wAFAP///wABAAAAAAAAAAAAAAAA
      AAEA////AAEA////AAAAAQAAAAAAAQAAAAAAAQAAAAAAAAAIAAAAAAABAA==
    signed: true
remaining: []