---
class: 4
flags: 0x0000
unid: OFDE5C9D0EAA4C06A2-ON0061B7C185257830
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: ".settings/.jsdtscope"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $Revisions
    type: time
    data:
      - data: "2011-02-07T12:47:20.43-05:00"
      - data: "2011-08-30T20:50:50.73-04:00"
        dst: true
      - data: "2011-10-06T16:05:44.56+01:00"
        dst: true
      - data: "2011-10-14T08:39:59.82+01:00"
        dst: true
  - name: $TITLE
    type: text
    data: ".settings/.jsdtscope"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []